version = 0.1
[default.deploy.parameters]
stack_name = "developer-sailpoint-site"
resolve_s3 = true
s3_prefix = "developer-sailpoint-site"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []