name: Build/Deploy to AWS S3 Staging

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ['stage']
    paths-ignore:
      - 'README.md'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Allow one concurrent deployment
concurrency:
  group: 'aws'
  cancel-in-progress: true

env:
  BASE_URL: '/'

permissions:
  id-token: write   # This is required for requesting the JWT
  contents: read

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS credentials from Test account
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: arn:aws:iam::176038645705:role/github-action-role
          role-session-name: deploy-to-staging
          aws-region: us-east-1
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Check out repo
        uses: actions/checkout@v3
      # Node is required for npm
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      # Install and build Developer Community site
      - name: Build Developer Community site
        run: |
          export NODE_OPTIONS="--max_old_space_size=4096"
          npm ci 
          npm run gen-api-docs-all
          npm run build

      # push these files to AWS
      - name: Copy files to the test website with the AWS CLI
        run: |
          aws s3 sync ./build s3://developer-sailpoint-site-developersailpointwebsite-kvgtkr2ctxdh

